version: '3.8'

services:
        
  download:
    image: docker.gnoss.com/demo-dockerdotnet
    environment:
     OutputFolder: "downloads"
     DownloadUrl: "http://web/home"
    volumes:
      - /home/gnoss/demo-riojadotnet/output:/app/downloads
    depends_on:
      - web

  web:
    image: demo-dockerweb
