version: '3.8'

services:
        
  download:
    image: docker.gnoss.com/demo-dockerdotnet:1.1
    environment:
     OutputFolder: "downloads"
     DownloadUrl: "http://web/home"
    volumes:
      - /home/gnoss/demo-riojadotnet/output:/app/downloads

  web:
    image: docker.gnoss.com/demo-dockerweb:1.1
